---
title: "Cerdeira_Diiuorio_TP4"
output: pdf_document
date: "2025-05-28"
---

```{r, echo = FALSE}
set.seed(1234)
datos_historicos = read.csv("datos_historicos.csv")$play.delay
datos_nueva_version = read.csv("datos_nueva_version.csv")$play.delay

```

### Ejercicio 1
### (a)

```{r, echo = FALSE}
media_muestral <- round(mean(datos_historicos),2)
var_muestral <- round(var(datos_historicos),2)

``` 

* La media muestral es `r media_muestral`.
* La varianza muestral es `r var_muestral`.

### (b)

``` {r, echo = FALSE}
hist(datos_historicos, prob = TRUE, col = "lightblue", main = "Histograma de densidad de datos historicos")
curve(dnorm(x, mean = media_muestral, sd = sqrt(var_muestral)), lwd = 2, lty = 2, add = TRUE, col = "darkred")

```

### Ejercicio 2

```{r, echo = FALSE}

mu_estimado = round(mean(datos_nueva_version),2)

```

La estimación de \(\mu\) es \( \hat{\mu} \) = \( \bar{X}\) = `r mu_estimado`.

### Ejercicio 3

### (a)

$$ H_0: \mu \leq \mu_0\quad vs.\quad H_1: \mu > \mu_0\quad $$ 

Es decir,

$$ H_0: \mu \leq 41.9846 \quad\text{vs}.\quad  H_1: \mu > 41.9846 $$

**Estadístico:** 

$$ \text{Para hallar el estadístico partimos del estimador de } \mu: $$ 

$$ \hat{\mu} = \overline{X} $$
$$ \text{Asumimos distribución de } \overline{X} \text{ bajo } H_0 $$
$$ \overline{X} \sim \mathcal{N}(\mu, \frac{52.43}{200})$$

Lo estandarizamos

$$T=\frac{\bar{X}-\mu}{\sqrt{\sigma^2 / n}} \sim \mathcal{N}(\mu, \frac{\sigma^2}{n}) \quad \text{bajo} \space H_0$$


### (b)

$$ \alpha = 0.05 $$



$$ \text{Vamos a rechazar}\space H_0 \space \text{cuando } \overline{X} > C \text{ donde } C \text{ es tal que:} \quad \alpha = P(EI) = P(\text{Rechazar } H_0 | H_0  \text{ es V}) = P(\overline{X}>C| H_0 \text{ es V})  $$
$$ \implies \text{Queremos C tal que } P(\overline{X}>C|H_0 \text{ es}) $$




